221029/day02/urls.py
from django.urls import path
from . import views

app_name = "day02"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/", views.detail, name="detail"),
    path("create/", views.create, name="create"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
]

221029/newday02/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("day02/", include("day02.urls")),
]

221029/day02/models.py
from django.db import models
from django.core.validators import MinValueValidator

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=30)
    summary = models.TextField()
    running_time = models.IntegerField(validators=[MinValueValidator(0)])

221029/day02/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = "__all__"

221029/day02/views.py
from multiprocessing import context
from django.shortcuts import render, redirect
from .forms import MovieForm
from .models import Movie

# Create your views here.
def index(request):
    reviews = Movie.objects.all()
    context = {
        "reviews": reviews,
    }
    return render(request, "day02/index.html", context)


def create(request):
    if request.method == "POST":
        m_form = MovieForm(request.POST)
        if m_form.is_valid():
            m_form.save()
            return redirect("day02:index")
    else:
        m_form = MovieForm()
    context = {
        "m_form": m_form,
    }
    return render(request, "day02/create.html", context)


def detail(request, pk):
    review = Movie.objects.get(pk=pk)
    context = {
        "review": review,
    }
    return render(request, "day02/detail.html", context)


def delete(request, pk):
    review = Movie.objects.get(pk=pk)
    review.delete()
    return redirect("day02:index")


def update(request, pk):
    review = Movie.objects.get(pk=pk)
    if request.method == "POST":
        m_form = MovieForm(request.POST, instance=review)
        if m_form.is_valid():
            m_form.save()
            return redirect("day02:detail", review.pk)
    else:
        m_form = MovieForm(instance=review)
    context = {
        "m_form": m_form,
    }
    return render(request, "day02/update.html", context)

221029/day02/templates/day02/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block body %}

<h1 class="title text-secondary text-center mt-5">영화 리뷰 작성</h1>
<form action="{% url 'day02:create' %}" method="post">
  {% csrf_token %}
  {% bootstrap_form m_form %}
  <input type="submit" value="추가" >
</form>

{% endblock body %}

221029/day02/templates/day02/detail.html
{% extends 'base.html' %}

{% block body %}

<h3 class="text-secondary mt-5">리뷰 제목 : {{ review.title }}</h3>
<p>상영 시간 : {{ review.running_time }}분</p>
<hr>
<p>{{ review.summary}}</p>
<button type="button" class="btn btn-success" onclick = "location.href = '{% url 'day02:update' review.pk %}' ">수정</button>
<button type="button" class="btn btn-danger" onclick = "location.href = '{% url 'day02:delete' review.pk %}' ">삭제</button>
{% endblock body %}

221029/day02/templates/day02/index.html
{% extends 'base.html' %}

{% block body %}

<h1 class="title text-secondary text-center mt-5">영화 리뷰 목록</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">No.</th>
      <th scope="col">리뷰 제목</th>
    </tr>
  </thead>
  <tbody>
    {% for review in reviews %}
    <tr>
      <th scope="row">{{ review.pk }}</th>
      <td><a href="{% url 'day02:detail' review.pk %}">{{ review.title }}</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>  
  
{% endblock body %}

221029/day02/templates/day02/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block body %}

<h1 class="title text-secondary text-center mt-5">영화 리뷰 수정</h1>
<form action="" method="post">
  {% csrf_token %}
  {% bootstrap_form m_form %}
  <input type="submit" value="수정" >
</form>

{% endblock body %}

221029/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static '' %}">
  <title>day02</title>

</head>
<body>
  <nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
      <h3 class="text-light">  
      <img src="{% static 'img/logo.png' %}" alt="Logo" width="70" height="40" class="d-inline-block align-text-top">
      KDT_01
      </h3>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" aria-current="page" href="{% url 'day02:index' %}">목록</a>
          <a class="nav-link" href="{% url 'day02:create' %}">추가</a>
        </div>
      </div>
    </div>
  </nav>
  <div class="container">
  {% block body %}
  
  {% endblock body %}
  </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</html>