221028/day01/urls.py
from django.urls import path
from . import views

app_name = "day01"

urlpatterns = [
    path("", views.index, name="index"),
    # path("new/", views.new, name="new"),
    path("create/", views.create, name="create"),
    path("<int:pk>/detail/", views.detail, name="detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/update/", views.update, name="update"),
]

221028/newday01/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("day01/", include("day01.urls")),
]

221028/day01/models.py
from django.db import models

# Create your models here.
class Day01(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

221028/day01/forms.py
from django import forms
from .models import Day01


class artsForm(forms.ModelForm):
    class Meta:
        model = Day01
        fields = "__all__"
        labels = {
            "title": "제목",
            "content": "내용",
        }

221028/day01/views.py
from django.shortcuts import render, redirect
from .models import Day01
from .forms import artsForm

# Create your views here.
def index(request):
    articles = Day01.objects.order_by("-pk")
    context = {
        "articles": articles,
    }
    return render(request, "day01/index.html", context)


# def new(request):
#     arts_form = artsForm()
#     context = {
#         "arts_form": arts_form,
#     }
#     return render(request, "day01/new.html", context)


def create(request):
    if request.method == "POST":
        arts_form = artsForm(request.POST)
        if arts_form.is_valid():
            arts_form.save()
            return redirect("day01:index")
    else:
        arts_form = artsForm()
    context = {
        "arts_form": arts_form,
    }
    return render(request, "day01/new.html", context)


def detail(request, pk):
    article = Day01.objects.get(pk=pk)

    context = {
        "arts": article,
    }
    return render(request, "day01/detail.html", context)


def delete(request, pk):
    article = Day01.objects.get(pk=pk)
    article.delete()
    return redirect("day01:index")


def update(request, pk):
    article = Day01.objects.get(pk=pk)
    if request.method == "POST":
        arts_form = artsForm(request.POST, instance=article)
        if arts_form.is_valid():
            arts_form.save()
            return redirect("day01:detail", article.pk)
    else:
        arts_form = artsForm(instance=article)
    context = {
        "arts_form": arts_form,
        "arts": article,
    }
    return render(request, "day01/update.html", context)

221028/day01/templates/day01/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container mt-5">
<h1>{{arts.title }}</h1>
<hr>
<h4>{{arts.content }}</h4>
<p>{{ arts.create_at }} | {{ arts.update_at }}</p>
<div>
  <a href="{% url 'day01:delete' arts.pk%}" class="btn btn-danger">Delete</a>
  <a href="{% url 'day01:update' arts.pk %}" class="btn btn-success">Update</a>
  <a href="{% url 'day01:index' %}" class="btn btn-primary">List</a>

</div>
</div>
{% endblock body %}

221028/day01/templates/day01/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <div class='container'>
    <h1 class='title text-center mt-5'>게시판</h1>
    <a class="btn btn-success" href="{% url 'day01:create' %}">신규작성</a>
    {% for arts in articles %}
    <hr>
    <a href="{% url 'day01:detail' arts.pk %}"><h3>{{ arts.title }}</h3></a>
    <p>{{ arts.create_at }} | {{ arts.update_at }}</p>
      
    {% endfor %}
  </div>

{% endblock body %}

221028/day01/templates/day01/new.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}

<h1 class='title text-center mt-5 fw-bold'>작성</h1>
<div class='container'>
  <form action="{% url 'day01:create' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form arts_form %}
    <input class="btn btn-success" type="submit" value="Success">
    <a href="{% url 'day01:index' %}"class="btn btn-danger">Cancel</a>
  </form>
</div>
{% endblock body %}

221028/day01/templates/day01/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}


{% block body %}

<h1 class='title text-center mt-5 fw-bold'>수정</h1>
<div class='container'>
<form action="{% url 'day01:update' arts.pk %}" method="POST">
  {% csrf_token %}
  {% bootstrap_form arts_form %}
  <input class="btn btn-success" type="submit" value="Update">
  <a href="{% url 'day01:detail' arts.pk %}"class="btn btn-danger">Cancel</a>
</form>
</div>

{% endblock body %}

221028/newday01/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Day01</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

</head>
<body>
  {% block body %}
  
  {% endblock body %}
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</html>